In [2]:
import numpy as np


In [3]:
#Indexacion de un solo elemento
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Extraccion de elementos en forma ascendente
x[3]

np.int64(3)

In [6]:
#Extraccion de elementos en forma descendente
x[-2]

np.int64(8)

In [9]:
#Convertir el arreglo anterior en formato bidimensional
x.shape = (2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
#extraccion de elemento con indice 1 en el renglon e indice 3 en la columna
x[1,3]

np.int64(8)

In [12]:
#Esta extraccion es la misma que la anterior
x[1][3]

np.int64(8)

In [14]:
#Extraccion con elementos descendentes
x[1,-1]

np.int64(9)

In [15]:
#Cuando se hace una extraccion con un solo indice se muestra solo un simple renglon
x[0]

array([0, 1, 2, 3, 4])

In [16]:
#Cortes en arreglos
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2] #Formato: "start:stop:step"

array([1, 3, 5])

In [17]:
x[-2:10] #Corte del arreglo de adelante hacia atras, considerando dos elemenmtos

array([8, 9])

In [18]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [19]:
#definicion de un nuevo arreglo
x = np.arange(10,1,-1) #Creacion de un arreglo en forma descendente - Del 10 al 1 (sin incluiro) - con decrementos
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [21]:
#Extraccion de elementos especificos del arreglo
x[np.array([3,3,1,8])] #Extraccion de elementos con indices 3 ,3 , 1, 8

array([7, 7, 9, 2])

In [23]:
x[np.array([3,3,-3,8])] #Este seria el resultado: 7,7,4,2 por que el indice negativo nos dice que se empieza de atras hacia adelante

array([7, 7, 4, 2])

In [24]:
#Extraccion basada en pares
y = np.arange(35).reshape(5,7) # Le estamos diciendo que sea un arreglo de 35 elementos con dimensiones de 5X7
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [26]:
#Extraccion 
y[np.array([0,2,4]),np.array([0,1,2])] #Exraccion de las coordenadas (0,0), (2,1) y (4,2)

array([ 0, 15, 30])

# Union de Arreglos

In [27]:
arr = np.concatenate(([1,2,3],[4,5,6]))
arr

array([1, 2, 3, 4, 5, 6])

In [28]:
#Apilado de vectores
np.stack(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#Concatenacion de matrice
mat_1 = np.array([[1,2,3],[4,5,6]])
mat_2 = np.array([[1,1,1],[2,2,2]])
np.concatenate((mat_1, mat_2), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [31]:
np.concatenate((mat_1, mat_2), axis = 1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [32]:
np.concatenate((mat_1, mat_2), axis = None)

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])