In [1]:
import numpy as np
accidentes = np.array([[0,1,1],
                     [1,0,1],
                     [1,3,2],
                     [2,2,0]])

In [4]:
#Suma de los accidentes (Suma del contenido del arreglo)
accidentes.sum()

np.int64(14)

In [5]:
#La suma de las columnas
accidentes_areas = accidentes.sum(axis = 0)
accidentes_areas

array([4, 6, 4])

In [7]:
print("Los accidentes del area 1:", accidentes_areas[0] )
print("Los accidentes del area 1:", accidentes_areas[1] )
print("Los accidentes del area 1:", accidentes_areas[2] )

Los accidentes del area 1: 4
Los accidentes del area 1: 6
Los accidentes del area 1: 4


In [11]:
#La suma de los renglones
accidentes_anios = accidentes.sum(axis = 1)
accidentes_anios

array([2, 2, 6, 4])

In [12]:
#La suma de los renglones
accidentes_anios = accidentes.sum(axis = 1, keepdims=True) #Keepdims mantiene la dimensionde del arreglo
accidentes_anios


array([[2],
       [2],
       [6],
       [4]])

In [13]:
print("Los accidentes del area 1:", accidentes_anios[0] )
print("Los accidentes del area 2:", accidentes_anios[1] )
print("Los accidentes del area 3:", accidentes_anios[2] )
print("Los accidentes del area 4:", accidentes_anios[3] )

Los accidentes del area 1: [2]
Los accidentes del area 2: [2]
Los accidentes del area 3: [6]
Los accidentes del area 4: [4]


In [17]:
#Sacar los maximos y minimos
maximo = accidentes.max()
minimo = accidentes.min()
print(f"El numero maximo de accidentes es :{maximo}")
print(f"El numero minimo de accidentes es: {minimo}")

El numero maximo de accidentes es :3
El numero minimo de accidentes es: 0


In [19]:
#promedio 
promedio = accidentes.mean()
promedio

np.float64(1.1666666666666667)

In [23]:
#Operaciones vectorizadas
#Hay que hacer la suma del [1,2,3] + 3
#                          [4,5,6]
#Se define el arreglo
arreglo = np.array([[1,2,3],
                   [4,5,6]])
dimensiones= arreglo.shape
print(dimensiones[0]) #Renglones
print(dimensiones[1]) #Columnas
print(arreglo[0][0]) # Conocer el primer valor del arreglo

2
3
1


In [40]:
#Hacer el ejercicio con un ciclo
import time
inicio = time.time()
arreglo_final = np.zeros((2,3))
for renglon in range(dimensiones[0]):
    for columnas in range(dimensiones[1]):
        arreglo_final[renglon][columnas] = arreglo[renglon][columnas] + 3
print(arreglo_final)
fin = time.time()
tiempo_final = inicio - fin
print(tiempo_final)

[[4. 5. 6.]
 [7. 8. 9.]]
-0.0018305778503417969


In [42]:
#Hacer el ejercicio con numpy
import time
inicio = time.time()
arreglo_final = arreglo + 3
print(arreglo_final)
fin = time.time()
tiempo_final = inicio - fin
print(tiempo_final)

[[4 5 6]
 [7 8 9]]
-0.0007903575897216797


In [2]:
#prueba
arreglo_chapis = np.array([[1, 2, 3, 4 ,5, 6],
                          [5.4, 6, 8, 9, 10, 7],
                         [7,9,10,78,98,10]])
arreglo_chapis2 = arreglo_chapis * .9
arreglo_chapis2 

array([[ 0.9 ,  1.8 ,  2.7 ,  3.6 ,  4.5 ,  5.4 ],
       [ 4.86,  5.4 ,  7.2 ,  8.1 ,  9.  ,  6.3 ],
       [ 6.3 ,  8.1 ,  9.  , 70.2 , 88.2 ,  9.  ]])

In [3]:
#Adiccion de 2 arreglos
arreglo1 = np.array([[1,2,3],
                    [4,5,6]])
arreglo2 = np.array([[7,8,9],
                    [10,11,12]])
arreglo3 = arreglo1 + arreglo2
arreglo3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [4]:
#Evaluacion de condiciones
arreglo1 = np.array([[1,2,3],
                    [4,5,6]])
arreglo1 > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [7]:
#Para que algunas funciones en python funciones con los arreglos estas deben de estar vectorizadas
#para vectorizar las funciones hay que usar la siguiente funcion
arreglo = np.array(["Numpy", "maneja", "vectorizacion"])
len_vectorizado = np.vectorize(len)
len_vectorizado(arreglo) > 2
#Con esto se evaluan las condicones de cada uno de los componentes del arreglo

array([ True,  True,  True])

In [10]:
#Broadcasting de reglones
arreglo_test = np.arange(10).reshape((2,5))
arreglo_test + np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [11]:
#Broadcastin de columnas
arreglo_test = np.arange(10).reshape((2,5))
arreglo_test + np.array([0,1]).reshape((2,1))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [13]:
arreglo1 = np.array([[1,2,3],
                    [4,5,6]])
arreglo2 = np.array([[7,8]])
arreglo3 = arreglo1 + arreglo2
arreglo3

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [14]:
#Volteo de un arreglo
arreglo = np.array([[1.1,1.2,1.3],
                   [2.1,2.2,2.3],
                   [3.1,3.2,3.3]])
np.flip(arreglo)

array([[3.3, 3.2, 3.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

In [15]:
#trasnsposicion de un arreglo
arreglo = np.array([[1.1,1.2,1.3],
                   [2.1,2.2,2.3],
                   [3.1,3.2,3.3]])
np.transpose(arreglo)

array([[1.1, 2.1, 3.1],
       [1.2, 2.2, 3.2],
       [1.3, 2.3, 3.3]])

In [16]:
#Operaciones con numpy
np.array([[1,2], [3,4]]) * np.array([[5], [10]])

array([[ 5, 10],
       [30, 40]])

In [17]:
#Operaciones con numpy 2
np.array([[1,2], [3,4]]) - np.array([[5], [10]])

array([[-4, -3],
       [-7, -6]])